#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..
./build
cat dist/hito.ttl dist/dbpedia.ttl dist/swo.ttl > dist/all.ttl
cd scripts
pyshacl -s ../shacl.ttl -a -f human ../dist/all.ttl | tee /tmp/shacl.txt
